requires:
  fbl: '>=1.12.0 <2.0.0'
  plugins:
    '@fbl-plugins/k8s-helm': '>=1.1.1'
    '@fbl-plugins/k8s-kubectl': '>=1.2.3'

pipeline:
  # Run multiple actions in a sequence
  # Ref: https://fbl.fireblink.com/plugins/flow#action-handler-sequential-steps-execution
  '--':
    # Invoke nested flow to prepare before starting the rollback
    # Ref: https://fbl.fireblink.com/plugins/flow#action-handler-attached-flow
    - '@': prepare.yml

    # Try to load "fbl-deployment" ConfigMap
    # Ref: https://fbl.fireblink.com/plugins/flow#action-handler-try-catch-finally-flow
    - $title: try to get "fbl-deployment" ConfigMap
      try:
        action:
          # Get the "fbl-deployment" ConfigMap
          # Ref: https://github.com/FireBlinkLTD/fbl-plugins-k8s-kubectl/blob/master/docs/GetOne.md
          kubectl.get.one:
            resource: ConfigMap
            name: fbl-deployment
            assignResourceTo: $.ctx.fbl.deployment

        catch:
          # Construct default "fbl-deployment" ConfigMap state
          # Ref: https://fbl.fireblink.com/plugins/context#action-handler-context-values-assignment
          $title: "fbl-deployment" ConfigMap not found, assigning default value
          ctx:
            $.fbl.deployment:
              inline:
                kind: ConfigMap
                apiVersion: v1
                metadata:
                  name: fbl-deployment
                data: {}

    # Check if release was not previously deployed based on ConfigMap value
    # Ref: https://fbl.fireblink.com/plugins/flow#action-handler-switch-flow
    - $title: check if release was already deployed
      if:
        value: <%- ctx.fbl.deployment.data[ctx.cli.release] === 'success' || ctx.fbl.deployment.data[ctx.cli.release] === 'failure' %>
        is:
          true:
            # Rise error
            # Ref: https://fbl.fireblink.com/plugins/flow#action-handler-error
            error: |-
              Could not deploy <%- ctx.cli.release %> release.
              It look like there was previous attempt to deploy it that completed with status "<%- ctx.fbl.deployment.data[ctx.cli.release] %>".
              Please rollback the deployment and try again.

    # Try to run the release deployment scripts
    # Ref: https://fbl.fireblink.com/plugins/flow#action-handler-try-catch-finally-flow
    - $title: try to make the deployment
      try:
        action:
          # Run multiple actions is a sequence
          # Ref:
          '--':
            # Process the deployment flow inside the release folder
            # Ref: https://fbl.fireblink.com/plugins/flow#action-handler-attached-flow
            - '@': releases/<%- ctx.cli.release %>/deploy

            # Mark deployment successful inside ConfigMap data
            # Ref: https://fbl.fireblink.com/plugins/exec#action-handler-function
            - $title: mark deployment as successfully completed
              fn: |-
                ctx.fbl.deployment.data[ctx.cli.release] = 'success'
        catch:
          # Mark deployment failed inside ConfigMap data
          # Ref: https://fbl.fireblink.com/plugins/exec#action-handler-function
          $title: mark deployment as failed
          fn: |-
            ctx.fbl.deployment.data[ctx.cli.release] = 'failure'

    # Update the "fbl-deployment" config map
    # Ref: https://github.com/FireBlinkLTD/fbl-plugins-k8s-kubectl/blob/master/docs/Apply.md
    - $title: update "fbl-deployment" ConfigMap
      kubectl.apply:
        inline:
          - $ref:ctx.fbl.deployment

    # Check if deployment was unsuccessful
    # Ref: https://fbl.fireblink.com/plugins/flow#action-handler-switch-flow
    - $title: check if deployment failed
      if:
        value: <%- ctx.fbl.deployment.data[ctx.cli.release] === 'failure' %>
        is:
          true:
            # Rise error
            # Ref: https://fbl.fireblink.com/plugins/flow#action-handler-error
            error: Release <%- ctx.cli.release %> failed to deploy
