requires:
  fbl: '>=1.12.0 <2.0.0'
  plugins:
    '@fbl-plugins/k8s-helm': '>=1.1.1'
    '@fbl-plugins/k8s-kubectl': '>=1.2.3'

pipeline:
  '--':
    - '@': prepare.yml

    - $title: get "fbl-deployment" ConfigMap
      kubectl.get.one:
        resource: ConfigMap
        name: fbl-deployment
        assignResourceTo: $.ctx.fbl.deployment

    - $title: check if release was previously fully or partially deployed
      if:
        value: <%- ctx.fbl.deployment.data[ctx.cli.release] === 'success' || ctx.fbl.deployment.data[ctx.cli.release] === 'failure'  %>
        is:
          false:
            error: Release <%- ctx.cli.release %> was not previously deployed.

    - $title: run the release rollback scripts
      '@': releases/<%- ctx.cli.release %>/rollback

    - $title: mark release as "reverted"
      fn: |-
        ctx.fbl.deployment.data[ctx.cli.release] = 'reverted';

    - $title: update "fbl-deployment" ConfigMap
      kubectl.apply:
        inline:
          - $ref:ctx.fbl.deployment
