pipeline:
  '--':
    - echo: ''
    # Execute command directly
    # Ref: https://fbl.fireblink.com/plugins/exec#action-handler-shell-command
    - exec:
        command: kubectl
        args:
          - '-n'
          - $ref:ctx.namespace
          - describe
          - $ref:ctx.kind
          - $ref:ctx.resource
        options:
          verbose: true
    - echo: ''
