pipeline:
  '--':
    - $title: read configuration from "config" folder
      ctx:
        $:
          files:
            - ../config/<$- ctx.cli.environment $>/*.yml

    - $title: rollback services
      '@': services/
