pipeline:
  virtual:
    id: selectWithAction
    dynamicWorkDir: true
    parametersSchema:
      type: object
      additionalProperties: false
      required:
        - options
        - assignTo
        - message
        - nextAction
        - backAction
      properties:
        # Back option label text
        backLabel:
          type: string
        # Options to show
        options:
          type: array
        # Assign selected resource name to given path
        assignTo:
          type: string
        # Define next action handler to invoke
        nextAction:
          type: object
        # Define action handler for "back" option
        backAction:
          type: object
        # Message to show for user to pick the option
        message:
          type: string
    action:
      '--':
        # Execute actions in a sequence and share parameters.
        # By default parameters are cloned for each action individually to sandbox parameters processing.
        # However in some cases like this it is handy to mutate parameters in one action to be used in a following one.
        # "shareParameters" flag allows to turn on that behavior.
        shareParameters: true
        actions:
          # Need to add "back" option value.
          # Ref: https://fbl.fireblink.com/plugins/exec#action-handler-function
          - fn: |-
              parameters.options = [
                {
                  title: parameters.backLabel || '[<] Back',
                  value: '@@back@@'
                },
                ... parameters.options
              ];

          # Present options to user to pick from
          # Ref: https://fbl.fireblink.com/plugins/prompts#action-handler-select
          - select:
              message: $ref:parameters.message
              options: $ref:parameters.options

              assignResponseTo: $ref:parameters.assignTo
              pushResponseTo: $.parameters.result

          # Invoke "printPath" virtual action handler defined in "./printPath.yml"
          - printPath: {}

          # Based on the selected option either call next or back action
          # Ref: https://fbl.fireblink.com/plugins/flow#action-handler-switch-flow
          - '?':
              value: <%- parameters.result[0] %>
              is:
                '@@back@@':
                  invoke: $ref:parameters.backAction
              else:
                invoke: $ref:parameters.nextAction
