pipeline:
  # Call virtual action handler to query resources in the given namespace and type.
  # Virtual is defined in "../utils/findAllAndSelect.yml"
  findAllAndSelect:
    resource: $ref:ctx.kind
    message: 'Select resource:'
    assignTo: '$.ctx.resource'
    namespace: $ref:ctx.namespace
    nextAction:
      '@': action.yml
    backAction:
      '@': kind.yml

